### ISSUE TITLE
Is it published on crates?

### ISSUE THREAD

**Issue by gustawdaniel** [nimrodshn/btree#4]
I have error:

```
error: no matching package named `btree` found
```

and

https://docs.rs/btree/

is empty

**Comment by maekoos** [comment]
I'm almost sure it is not, considering it is still WIP... If you would like to use it though, i would recommend using the [git repository as a crate](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories).

**Comment by nimrodshn** [comment]
@gustawdaniel Correct - I did not publish it. If you would like - I can publish it as a crate. However, use at you're own risk - this code hasn't been used in production settings.

Alternatively, use the suggestion of @maekoos .

**Comment by nimrodshn** [comment]
@gustawdaniel Published in crates.io under `nimrodshn-btree v0.1.0`. Use with care under MIT license :)
